### ISSUE TITLE
FEDVR has AbstractVector field

### ISSUE THREAD

**Issue by jagot** [JuliaApproximation/CompactBases.jl#17]
[`FEDVR.t`](https://github.com/JuliaApproximation/CompactBases.jl/blob/78be896be85ff3a507aeb92ed46c297f7e0bb44b/src/fedvr.jl#L4) is an `AbstractVector`. Is changing this breaking according to SemVer?

**Comment by dlfivefifty** [comment]
I would say no, in any case v0.x.x is experimental so need to be overly pedantic

**Comment by dlfivefifty** [comment]
(Or another way to think of it: it's only a breaking change if it actually breaks extant code in dependent packages.)
